services:
  - type: web
    name: smart-attendance-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
    repo: https://github.com/Vardhan158/smart-attendance
    branch: main
    rootDir: backend
